"""sandbox.py — the execution boundary the gate runs test commands behind.

The gate executes test code it does not trust. Isolation is a host concern, so
this is a small adapter seam, not a bundled security guarantee:

  SubprocessSandbox   weak: a child process with a timeout and a scrubbed-ish
                      env. NOT a security boundary. Correct when the gate ALREADY
                      runs inside an isolated CI job / container (the common case)
                      — there the CI runner is the sandbox and this just shells
                      out within it.
  ContainerSandbox    runs the command inside `docker run --rm` with the
                      workspace bind-mounted read-write and network off by
                      default. The recommended isolation for running genuinely
                      untrusted agent code on a shared host. Requires Docker on
                      PATH; constructed lazily so importing this module never
                      needs Docker.

Both satisfy the `Sandbox` protocol, so the runner is agnostic to which is used.

Stdlib only.
"""

from __future__ import annotations

import subprocess
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Protocol


@dataclass(frozen=True, slots=True)
class ExecResult:
    returncode: int
    stdout: str
    stderr: str
    timed_out: bool


class Sandbox(Protocol):
    # Short, honest isolation label recorded on a verdict's audit trail (e.g.
    # "subprocess", "container"). A consumer must never read a stronger guarantee
    # off a weaker label.
    label: str

    def run(
        self,
        command: Sequence[str],
        *,
        cwd: Path,
        env: Mapping[str, str] | None = None,
        timeout: float | None = None,
    ) -> ExecResult: ...


def _complete(proc_args, *, cwd, env, timeout) -> ExecResult:
    try:
        proc = subprocess.run(  # noqa: S603 — command comes from anchored config
            list(proc_args),
            cwd=str(cwd),
            env=env,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
    except subprocess.TimeoutExpired as exc:
        return ExecResult(
            returncode=124,
            stdout=exc.stdout or "" if isinstance(exc.stdout, str) else "",
            stderr=(exc.stderr or "" if isinstance(exc.stderr, str) else "")
            + f"\n[relyable] command timed out after {timeout}s",
            timed_out=True,
        )
    return ExecResult(
        returncode=proc.returncode,
        stdout=proc.stdout,
        stderr=proc.stderr,
        timed_out=False,
    )


class SubprocessSandbox:
    """Weak isolation. Use only when the gate already runs inside an isolated
    CI job/container, or for trusted self-checks. Not a security boundary."""

    label = "subprocess"

    def __init__(self, *, inherit_env: bool = True) -> None:
        self._inherit_env = inherit_env

    def run(
        self,
        command: Sequence[str],
        *,
        cwd: Path,
        env: Mapping[str, str] | None = None,
        timeout: float | None = None,
    ) -> ExecResult:
        import os  # noqa: PLC0415

        base = dict(os.environ) if self._inherit_env else {}
        if env:
            base.update(env)
        # Keep generated bytecode out of the workspace (avoids polluting a tree
        # the gate may also integrity-check).
        base.setdefault("PYTHONDONTWRITEBYTECODE", "1")
        return _complete(command, cwd=cwd, env=base, timeout=timeout)


class ContainerSandbox:
    """Run the command inside `docker run --rm` with the workspace bind-mounted.

    Network is disabled by default (--network none); pass allow_network=True for
    suites that genuinely need it. The image must already contain the language
    toolchain. Recommended for untrusted code on a shared host.
    """

    label = "container"

    def __init__(
        self,
        image: str,
        *,
        allow_network: bool = False,
        docker_bin: str = "docker",
        workdir: str = "/workspace",
    ) -> None:
        self.image = image
        self.allow_network = allow_network
        self.docker_bin = docker_bin
        self.workdir = workdir

    def run(
        self,
        command: Sequence[str],
        *,
        cwd: Path,
        env: Mapping[str, str] | None = None,
        timeout: float | None = None,
    ) -> ExecResult:
        docker_cmd = [
            self.docker_bin,
            "run",
            "--rm",
            "-v",
            f"{cwd.resolve()}:{self.workdir}",
            "-w",
            self.workdir,
        ]
        if not self.allow_network:
            docker_cmd += ["--network", "none"]
        for key, value in (env or {}).items():
            docker_cmd += ["-e", f"{key}={value}"]
        docker_cmd.append(self.image)
        docker_cmd += list(command)
        # cwd for the docker client itself is irrelevant; the mount carries it.
        return _complete(docker_cmd, cwd=cwd, env=None, timeout=timeout)
